# Generated by Django 4.2.1 on 2023-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobikode_app', '0002_alter_employ_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='Availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='CTC',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='ECTC',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Offer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='PassPort',
            field=models.CharField(blank=True, choices=[('Yes', '✅'), ('No', '❌')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Reason_for_job_change',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Relevant_Experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employ',
            name='Skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
